[package]
name = "weatherCli"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.10"
reqwest = { version = "0.11", features = ["json","blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
